server:
  port: {{ default .SERVER_PORT 8080 }}

database:
  host: {{ default .DATABASE_HOST "localhost" }}
  port: {{ default .DATABASE_PORT 5432 }}
  name: {{ default .DATABASE_NAME "insider" }}
  username: {{ default .DATABASE_USERNAME "postgres" }}
  password: {{ default .DATABASE_PASSWORD "postgres" }}
  logLevel: {{ default .DATABASE_LOG_LEVEL 1 }}
  pool:
    maxIdleConnections: {{ default .DATABASE_MAX_IDLE_CONNECTIONS 5 }}
    maxOpenConnections: {{ default .DATABASE_MAX_OPEN_CONNECTIONS 100 }}
    connectionMaxLifetime: {{ default .DATABASE_CONNECTION_MAX_LIFETIME 60000 }}
    connectionMaxIdleTime: {{ default .DATABASE_CONNECTION_MAX_IDLE_TIME 1000 }}

rabbitmq:
  host: {{ default .RABBITMQ_HOST "localhost" }}
  port: {{ default .RABBITMQ_PORT 5672 }}
  vhost: {{ default .RABBITMQ_VHOST "insider" }}
  username: {{ default .RABBITMQ_USERNAME "guest" }}
  password: {{ default .RABBITMQ_PASSWORD "guest" }}

scheduler:
  interval: {{ default .SCHEDULER_INTERVAL "10s" }}
  itemCountPerCycle: {{ default .SCHEDULER_ITEM_COUNT_PER_CYCLE 2 }}

provider:
  type: webhook.site
  url: "http://localhost:5000/webhook"
  requestTimeout: 5s
  circuitBreaker:
    maxRequests: 5
    maxFailure: 5
    interval: 60s
    timeout: 5s